import { BREAK_POINTS, LOCAL_STORAGE_KEY } from 'constants/constants';

export const futuresGridKey = {
    favoritePair: 'favoritePair',
    pairDetail: 'pairDetail',
    chart: 'chart',
    orderBook: 'orderBook',
    recentTrades: 'recentTrades',
    tradeRecord: 'tradeRecord',
    placeOrder: 'placeOrder',
    marginRatio: 'marginRatio',
}

export const getLayoutFromLS = (key) => {
    let ls = {}
    if (global.localStorage) {
        try {
            ls =
                JSON.parse(
                    global.localStorage.getItem(
                        LOCAL_STORAGE_KEY.FuturesGridLayouts
                    )
                ) || {}
        } catch (e) {
            /*Ignore*/
        }
    }
    return ls[key]
}

export const setLayoutToLS = (key, value) => {
    if (global.localStorage) {
        let localStorage = global.localStorage.getItem(
            LOCAL_STORAGE_KEY.FuturesGridLayouts
        )
        if (localStorage) {
            localStorage = JSON.parse(localStorage);
            localStorage[key] = value;
            global.localStorage.setItem(
                LOCAL_STORAGE_KEY.FuturesGridLayouts,
                JSON.stringify(localStorage)
            )
        } else {
            global.localStorage.setItem(
                LOCAL_STORAGE_KEY.FuturesGridLayouts,
                JSON.stringify({
                    [key]: value
                })
            )
        }
    }
}

export default {
    cols: {
        md: 12,
        lg: 14,
        xl: 16,
        '2xl': 18,
    },
    breakpoints: {
        md: BREAK_POINTS.md,
        lg: BREAK_POINTS.lg,
        xl: BREAK_POINTS.xl,
        '2xl': BREAK_POINTS['2xl'],
    },
    layouts: {
        md: [
            {
                w: 9,
                h: 2,
                x: 0,
                y: 1,
                i: futuresGridKey.favoritePair,
                moved: false,
                static: false,
                isDraggable: false,
                isResizable: true,
            },
            {
                w: 9,
                h: 3,
                x: 0,
                y: 0,
                i: futuresGridKey.pairDetail,
                moved: false,
                static: false,
                isDraggable: false,
                isResizable: true,
            },
            {
                w: 9,
                h: 29,
                x: 0,
                y: 0,
                i: futuresGridKey.chart,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
            {
                w: 4.5,
                h: 13,
                x: 4.5,
                y: 24,
                i: futuresGridKey.orderBook,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
            {
                w: 4.5,
                h: 13,
                x: 0,
                y: 24,
                i: futuresGridKey.recentTrades,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
            {
                w: 9,
                h: 13,
                x: 0,
                y: 27,
                i: futuresGridKey.tradeRecord,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
            {
                w: 3,
                h: 34,
                x: 10,
                y: 3,
                i: futuresGridKey.placeOrder,
                minW: 4,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
            {
                w: 3,
                h: 24,
                x: 10,
                y: 32,
                i: futuresGridKey.marginRatio,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
        ],
        lg: [
            {
                w: 14,
                h: 2,
                x: 0,
                y: 0,
                i: futuresGridKey.favoritePair,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
            {
                w: 14,
                h: 3,
                x: 0,
                y: 0,
                i: futuresGridKey.pairDetail,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
            {
                w: 10,
                h: 20,
                x: 0,
                y: 3,
                i: futuresGridKey.chart,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
            {
                w: 5,
                h: 13,
                x: 5,
                y: 19,
                i: futuresGridKey.orderBook,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
            {
                w: 5,
                h: 13,
                x: 0,
                y: 19,
                i: futuresGridKey.recentTrades,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
            {
                w: 10,
                h: 13,
                x: 0,
                y: 32,
                i: futuresGridKey.tradeRecord,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
            {
                w: 4,
                h: 33,
                x: 10,
                y: 3,
                i: futuresGridKey.placeOrder,
                minW: 4,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
            {
                w: 4,
                h: 13,
                x: 10,
                y: 32,
                i: futuresGridKey.marginRatio,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
        ],
        xl: [
            {
                w: 8,
                h: 2,
                x: 0,
                y: 0,
                i: futuresGridKey.favoritePair,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
            {
                w: 8,
                h: 3,
                x: 0,
                y: 0,
                i: futuresGridKey.pairDetail,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
            {
                w: 8,
                h: 29,
                x: 0,
                y: 3,
                i: futuresGridKey.chart,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
            {
                w: 4,
                h: 21,
                x: 8,
                y: 0,
                i: futuresGridKey.orderBook,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
            {
                w: 4,
                h: 11,
                x: 8,
                y: 21,
                i: futuresGridKey.recentTrades,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
            {
                w: 12,
                h: 11,
                x: 0,
                y: 32,
                i: futuresGridKey.tradeRecord,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
            {
                w: 4,
                h: 32,
                x: 12,
                y: 0,
                i: futuresGridKey.placeOrder,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
            {
                w: 4,
                h: 11,
                x: 12,
                y: 32,
                i: futuresGridKey.marginRatio,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
        ],
        '2xl': [
            {
                h: 2,
                i: futuresGridKey.favoritePair,
                moved: false,
                static: false,
                w: 12,
                x: 0,
                y: 0,
            },
            {
                w: 12,
                h: 3,
                x: 0,
                y: 0,
                i: futuresGridKey.pairDetail,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
            {
                w: 12,
                h: 26,
                x: 0,
                y: 3,
                i: futuresGridKey.chart,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
            {
                w: 3,
                h: 19,
                x: 12,
                y: 0,
                i: futuresGridKey.orderBook,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
            {
                w: 3,
                h: 10,
                x: 12,
                y: 19,
                i: futuresGridKey.recentTrades,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
            {
                w: 15,
                h: 13,
                x: 0,
                y: 5,
                i: futuresGridKey.tradeRecord,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
            {
                w: 3,
                h: 29,
                x: 15,
                y: 0,
                i: futuresGridKey.placeOrder,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
            {
                w: 3,
                h: 15,
                x: 15,
                y: 29,
                i: futuresGridKey.marginRatio,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
        ],
    },
    layoutsVndc: {
        md: [
            {
                w: 9,
                h: 2,
                x: 0,
                y: 0,
                i: futuresGridKey.favoritePair,
                moved: false,
                static: false,
                isDraggable: false,
                isResizable: true,
            },
            {
                w: 9,
                h: 3,
                x: 0,
                y: 0,
                i: futuresGridKey.pairDetail,
                moved: false,
                static: false,
                isDraggable: false,
                isResizable: true,
            },
            {
                w: 9,
                h: 29,
                x: 0,
                y: 5,
                i: futuresGridKey.chart,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
            {
                w: 9,
                h: 15,
                x: 0,
                y: 5,
                i: futuresGridKey.tradeRecord,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
            {
                w: 3,
                h: 36,
                x: 9,
                y: 0,
                i: futuresGridKey.placeOrder,
                minW: 4,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
            {
                w: 3,
                h: 13,
                x: 9,
                y: 32,
                i: futuresGridKey.marginRatio,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
        ],
        lg: [
            {
                w: 10,
                h: 2,
                x: 0,
                y: 0,
                i: futuresGridKey.favoritePair,
                moved: false,
                static: false,
                isDraggable: false,
                isResizable: true,
            },
            {
                w: 10,
                h: 3,
                x: 0,
                y: 0,
                i: futuresGridKey.pairDetail,
                moved: false,
                static: false,
                isDraggable: false,
                isResizable: true,
            },
            {
                w: 10,
                h: 29,
                x: 0,
                y: 5,
                i: futuresGridKey.chart,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
            {
                w: 10,
                h: 14,
                x: 0,
                y: 5,
                i: futuresGridKey.tradeRecord,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
            {
                w: 4,
                h: 36,
                x: 10,
                y: 0,
                i: futuresGridKey.placeOrder,
                minW: 4,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
            {
                w: 4,
                h: 12,
                x: 10,
                y: 32,
                i: futuresGridKey.marginRatio,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
        ],
        xl: [
            {
                w: 12,
                h: 2,
                x: 0,
                y: 0,
                i: futuresGridKey.favoritePair,
                moved: false,
                static: false,
                isDraggable: false,
                isResizable: true,
            },
            {
                w: 12,
                h: 3,
                x: 0,
                y: 0,
                i: futuresGridKey.pairDetail,
                moved: false,
                static: false,
                isDraggable: false,
                isResizable: true,
            },
            {
                w: 12,
                h: 33,
                x: 0,
                y: 5,
                i: futuresGridKey.chart,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
            {
                w: 12,
                h: 13,
                x: 0,
                y: 5,
                i: futuresGridKey.tradeRecord,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
            {
                w: 4,
                h: 38,
                x: 15,
                y: 0,
                i: futuresGridKey.placeOrder,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
            {
                w: 4,
                h: 13,
                x: 15,
                y: 32,
                i: futuresGridKey.marginRatio,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
        ],
        '2xl': [
            {
                w: 15,
                h: 2,
                x: 0,
                y: 0,
                i: futuresGridKey.favoritePair,
                moved: false,
                static: false,
                isDraggable: false,
                isResizable: true,
            },
            {
                w: 15,
                h: 3,
                x: 0,
                y: 0,
                i: futuresGridKey.pairDetail,
                moved: false,
                static: false,
                isDraggable: false,
                isResizable: true,
            },
            {
                w: 15,
                h: 30,
                x: 0,
                y: 5,
                i: futuresGridKey.chart,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
            {
                w: 15,
                h: 12,
                x: 0,
                y: 5,
                i: futuresGridKey.tradeRecord,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
            {
                w: 3,
                h: 35,
                x: 15,
                y: 0,
                i: futuresGridKey.placeOrder,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
            {
                w: 3,
                h: 12,
                x: 34,
                y: 29,
                i: futuresGridKey.marginRatio,
                moved: false,
                static: false,
                isDraggable: true,
                isResizable: true,
            },
        ],
    },
}
